# Generated by Django 5.2.7 on 2025-11-01 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
        ("main", "0002_message_author_recipient_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="recipient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="main.recipient",
                verbose_name="Получатель",
            ),
            preserve_default=False,
        ),
    ]
